{% set name = "enstat" %}
{% set org = "tdegeus" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c5b92d446f5d4b654421f6c0fc174af3fb676f722b39689df1d175b65e76444c

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - numpy
    - python >=3

test:
  requires:
    - pip
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Iterative ensemble averages
  description: Iterative ensemble averages
  doc_url: https://{{ name }}.readthedocs.io/
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
